### ISSUE TITLE
Instructor Feedback Week 5 - Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [cgreger/GW2Auxiliary#5]
Looks like you are making good regular progress! Nice job getting something up to AWS too!

- [x] A note about issues/feedback. You add an "X" to check off the checkboxes to indicate you have completed the work or responded to the questions. When all done, then you can close the issue. See example:
- [x] A completed task.
- [x] Is your db design doc up-to-date? Looks like you have a LOT of entities (good work) - do they each have a corresponding table or?
- [x] Something to keep in mind in general - if there were an error in the userDao, what would the user experience be? You might consider throwing an exception (you can create your own exceptions) that the controller would catch and then route the user to a friendly-looking error page.
- [x] Great work so far - thanks for your good participation in class and willingness to share what you've learned in scrum, slack and in discussions. Keep it up!

**Comment by cgreger** [comment]
Yes, my db design doc needs to be updated. I have so many entities because those are all the item classes in the game.

I could use some advice for how to go about getting the item information. My current database design is so simple because I was planning on sending an API request when item information is needed, and then storing that item as an instance of a class. This means I only need to store the item's game id.  

I was trying to avoid having to basically "download" every item into my database, and instead only request the ones that I needed. (there are thousands) But as I get further, I think I may have to download and store the all the item information. Especially if I want suggestive search to work in my project. Do API requests significantly slow down an application?

What do you suggest is a good way to do this? If it turns out that I do need to download all the items, I have already read resources for how to do it so I don't think it would be much of a burden.

**Comment by pawaitemadisoncollege** [comment]
Hi Chelsea, just wanted to document our conversation here: Sorry about not catching your question. So the decision is: download and store the data or use the service to request it as needed?

[5:49]  
1. How much might the data change?

[5:51]  
2. Have you tried a service call at all (even in the browser) to see how performant it is?

[5:51]  
Generally an api request could be slow if there is a lot of data returned (similar to a db query that returns a lot)

cgreger [5:55 PM] 
The data is only displayed, not changed in anyway. And I have tried in the browser with many request. Every request responds instantly.

[5:56]  
it is just that i may have many requests per page

Paula Waite [5:56 PM] 
by change, i mean do the items available change? So if you were to store it, would you need to re-query the service occasionally to get the latest data?

cgreger [5:57 PM] 
oh! the parts i use only change every time they patch the game. I would probably just have it auto update at the end of every night or something?

[5:57]  
if I did store all of them

Paula Waite [5:57 PM] 
ok, makes sense.

[5:59]  
one more question - is there a limit to the number of calls you can make to the service?

[5:59]  
some service limit it, to say 1000/day, for example

cgreger [6:02 PM] 
The most recent documentation of limits I could find is from their dev team in May 2016. They said there are no limits, just to not make unnecessary requests (like requests of all items every 5 minutes)

[6:03]  
which my app wouldn't do

Paula Waite [6:04 PM] 
ok, cool, then my recommendation is to plan to use the service. Build that data access as a DAO, so that if it turns out that retrieving the data from the service gets to be too much (too slow, for example), then you simply change the dao to access your db instead.  What do you think?

cgreger [6:05 PM] 
sounds like a good plan!

Paula Waite [6:05 PM] 
Essentially, the only part of your program that should have to change is the dao layer if you decided to switch from service to db.
